# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  filters:
  - number: 1007
  - number: 1015
  - number: 58
  output: '%f-%i%I%v-%S.%x'

variants:
  - name: controller
    type: ibom
    sub_pcbs:
    - name: Controller
      reference: B1

  - name: ui
    type: ibom
    sub_pcbs:
    - name: UI
      reference: B2

import:
- file: CheckZoneFill
- file: board.kibot.yaml
  definitions:
    VARIANT: controller[Controller]
- file: board.kibot.yaml
  definitions:
    VARIANT: ui[UI]

outputs:

- name: download_datasheets
  comment: Datasheets for components
  type: download_datasheets
  dir: Datasheets

- name: basic_info
  comment: Information about the run
  type: info
  dir: .
- name: basic_kikit_present
  comment: Simple project presentation
  type: kikit_present
  dir: Presentation
  options:
    description: ../README.md
    boards:
    - mode: local
      name: Controller
      comment: Resources included
      front_image: pcbdraw-top-controller[Controller]
      back_image: pcbdraw-bottom-controller[Controller]
      gerbers: present-gerber-controller[Controller]
      pcb_from_output: present-variant-controller[Controller]
    - mode: local
      name: User Interface
      comment: Resources included
      front_image: pcbdraw-top-ui[UI]
      back_image: pcbdraw-bottom-ui[UI]
      gerbers: present-gerber-ui[UI]
      pcb_from_output: present-variant-ui[UI]

- name: schematic-pdf
  comment: Schematic in PDF format
  type: pdf_sch_print
  dir: Schematic

- name: web-navigation
  comment: Web page to browse the results
  type: navigate_results
  dir: Browse
  options:
    link_from_root: index.html
    skip_not_run: true

...
definitions:
  _KIBOT_MANF_DIR_COMP: Manufacturers
  _KIBOT_GERBER_LAYERS: "- layer: 'F.Cu'\n        suffix: 'F_Cu'\n        description:\
    \ 'Front copper'\n      - layer: 'B.Cu'\n        suffix: 'B_Cu'\n        description:\
    \ 'Bottom copper'\n      - layer: 'F.Paste'\n        suffix: 'F_Paste'\n     \
    \   description: 'Front solder paste'\n      - layer: 'B.Silkscreen'\n       \
    \ suffix: 'B_Silkscreen'\n        description: 'Bottom silkscreen (artwork)'\n\
    \      - layer: 'F.Silkscreen'\n        suffix: 'F_Silkscreen'\n        description:\
    \ 'Front silkscreen (artwork)'\n      - layer: 'B.Mask'\n        suffix: 'B_Mask'\n\
    \        description: 'Bottom soldermask (negative)'\n      - layer: 'F.Mask'\n\
    \        suffix: 'F_Mask'\n        description: 'Front soldermask (negative)'\n\
    \      - layer: 'Edge.Cuts'\n        suffix: 'Edge_Cuts'\n        description:\
    \ 'Board shape'"
